development:
  adapter: postgresql
  encoding: unicode
  database: nt_dev
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: nt_test
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: nt_prod
  pool: 2
  username: ziyu
  password:
