development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 10

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 10

production:
  adapter: postgresql
  encoding: unicode
  pool: 10
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
