development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 2

  
production:
  adapter: postgresql
  encoding: unicode
  pool: 15
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
