development:
  adapter: postgresql
  encoding: unicode
  database: nt_dev
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: nt_test
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
